apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCRZftWD67JqwwRzcLv4qe92BXriwLuB14nhXrOWGf4VYGbhK1awdmGu9OaiTkpUSM/pVsKeXKP8fwjt7hn8L8qw/irntxWVT3FfAsOwEgV0F1CawLx1T8m5UFlir9/rItum7dK7QGf8qBtdcAExVPyildh71M+CV8/fMOgIK+JZh9p31Cphsxk5OUAlySqhUPZ+mJOcgxagyG9QYMYh7TVddABy0zxKNt1asCeDl62yuWvhr5gHzmvlwDrV8+IuQUpoVkMeOfBbWzZuqj/nvwWxNwgOtfE0TJfI8H1lQAfTqu88QShlMb15l1jowDW3NPDQBte/9QMGP+Wis6kxg2wMX7NrmrpavSikTuGWWv3CbOz55yzCV5syScY6N99z1BizwTeKbyVkPyEt9cRfhUPVl0kwzXNm8xLSS4vYeijfrCOoTyly10ifftfkrBUpmp5VllSlQXKSnBJpZjfKyfwIjEarnXBnhKRovi9PdSD1D6cKyeFvzUCG67PwU1WJ9TT90f7dsxi76YMpxHtkAzwU5MiGSW8gLBbK6FexHxd3IiXW5SaEOBg+6Ylv0BBpVe4vSreU6wzLxGFWNlMmMjDbjqO8q0FfjwDIqf2jXuigbvxa3DQqTCcQvdTUNGWPJ8EKCyqy/2CZx/qE3EAxHITbdxOWJXJ1+V+rVe/3TUwFqi8h0jVxXsqThBXJWMebaYHlyoM0YGDGRM3isXsSXQh5JoWTLBuwqTb
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

